#!/usr/bin/env python

#
# This is an extension to the Nautilus file manager to allow better 
# integration with the Subversion source control system.
# 
# Copyright (C) 2006-2008 by Jason Field <jason@jasonfield.com>
# Copyright (C) 2007-2008 by Bruce van der Kooij <brucevdkooij@gmail.com>
# Copyright (C) 2008-2008 by Adam Plumb <adamplumb@gmail.com>
# 
# RabbitVCS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# RabbitVCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with RabbitVCS;  If not, see <http://www.gnu.org/licenses/>.
#

import os.path
import sys
from optparse import OptionParser

from rabbitvcs.lib.helper import launch_ui_window

usage = """Usage: rabbitvcs <module> [path1] [path2] ...

Available Modules
------------------
about, add, blame, changes, checkout, cleanup, commit, create, delete, diff,
export, ignore, import, lock, log, merge, properties, relocate, rename,
resolve, revert, settings, switch, unlock, update, updateto

For module specific help type: rabbitvcs <module> -h
"""

args = sys.argv

if len(args) < 2 or args[1] == "-h":
    raise SystemExit(usage)

args.pop(0) # remove this file's path
module = args.pop(0)

launch_ui_window(module, args)
